#pragma once

/********************************************
 * SDK Generated by: SAQER
 * Telegram Contact: @EEXKX
 * Game: PUBG MOBILE (4.2.0)
 ********************************************/

namespace SDK
{
//----------------------------- SAQER ------------------------------
//Script Structs
//----------------------------- SAQER ------------------------------

// ScriptStruct TemBPNode.TemBPDataAddr
// 0x0018
struct FTemBPDataAddr
{
	uint64_t                                           Value;                                                    // 0x0000(0x0008) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x10];                                      // 0x0008(0x0010) MISSED OFFSET
};

}

