#pragma once

/********************************************
 * SDK Generated by: SAQER
 * Telegram Contact: @EEXKX
 * Game: PUBG MOBILE (4.2.0)
 ********************************************/

namespace SDK
{
//----------------------------- SAQER ------------------------------
//Classes
//----------------------------- SAQER ------------------------------

// Class YGamePipeline.YGamePipelineHelper
// 0x0028 (0x0050 - 0x0028)
class UYGamePipelineHelper : public UObject
{
public:
	struct FScriptMulticastDelegate                    PipeDataRevMsg;                                           // 0x0028(0x0010) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	struct FScriptMulticastDelegate                    PipeDataRevMsgT;                                          // 0x0038(0x0010) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	unsigned char                                      UnknownData00[0x8];                                       // 0x0048(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class YGamePipeline.YGamePipelineHelper");
		return pStaticClass;
	}


	bool SendDataWithKey(const struct FString& MsgKey, TArray<unsigned char> Data);
	bool SendData(const struct FString& MsgInfo);
	void Release();
	bool RecvdDataWithKeyTest(const struct FString& MsgKey);
	bool RecvDataTest(const struct FString& MsgInfo);
	void Log(const struct FString& LogInfo);
	bool IsConnected();
	bool Init();
	static class UYGamePipelineHelper* Get();
};


}

