#pragma once

/********************************************
 * SDK Generated by: SAQER
 * Telegram Contact: @EEXKX
 * Game: PUBG MOBILE (4.2.0)
 ********************************************/

namespace SDK
{
//----------------------------- SAQER ------------------------------
//Script Structs
//----------------------------- SAQER ------------------------------

// ScriptStruct MRMesh.MRMeshConfiguration
// 0x0001
struct FMRMeshConfiguration
{
	unsigned char                                      UnknownData00[0x1];                                       // 0x0000(0x0001) MISSED OFFSET
};

}

