#pragma once

/********************************************
 * SDK Generated by: SAQER
 * Telegram Contact: @EEXKX
 * Game: PUBG MOBILE (4.2.0)
 ********************************************/

namespace SDK
{
//----------------------------- SAQER ------------------------------
//Enums
//----------------------------- SAQER ------------------------------

// Enum IOSDeviceProfileSelector.ECompareType
enum class ECompareType : uint8_t
{
	CMP_Equal                      = 0,
	CMP_Less                       = 1,
	CMP_LessEqual                  = 2,
	CMP_Greater                    = 3,
	CMP_GreaterEqual               = 4,
	CMP_NotEqual                   = 5,
	CMP_Regex                      = 6,
	CMP_MAX                        = 7
};


// Enum IOSDeviceProfileSelector.ESourceType
enum class ESourceType : uint8_t
{
	SRC_PreviousRegexMatch         = 0,
	SRC_DeviceModel                = 1,
	SRC_iOSVersion                 = 2,
	SRC_MAX                        = 3
};



//----------------------------- SAQER ------------------------------
//Script Structs
//----------------------------- SAQER ------------------------------

// ScriptStruct IOSDeviceProfileSelector.ProfileMatchItem
// 0x0018
struct FProfileMatchItem
{
	TEnumAsByte<ESourceType>                           SourceType;                                               // 0x0000(0x0001) (ZeroConstructor, IsPlainOldData)
	TEnumAsByte<ECompareType>                          CompareType;                                              // 0x0001(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x6];                                       // 0x0002(0x0006) MISSED OFFSET
	struct FString                                     MatchString;                                              // 0x0008(0x0010) (ZeroConstructor)
};

// ScriptStruct IOSDeviceProfileSelector.ProfileMatch
// 0x0020
struct FProfileMatch
{
	struct FString                                     Profile;                                                  // 0x0000(0x0010) (ZeroConstructor)
	TArray<struct FProfileMatchItem>                   Match;                                                    // 0x0010(0x0010) (ZeroConstructor)
};

}

